- .travis.yml
- fog-libvirt.gemspec
- libvirt-dev is now being installed during before_install phase
- removed unused dev depedencies: redcarpet and thor
> Fixed build issues

- lib/fog/libvirt/compute.rb
- lib/fog/libvirt/models/compute/network.rb
- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/dhcp_leases.rb
- lib/fog/libvirt/requests/compute/list_networks.rb
- tests/libvirt/compute_tests.rb
- tests/libvirt/models/compute/network_tests.rb
- tests/libvirt/models/compute/server_tests.rb
- tests/libvirt/requests/compute/dhcp_leases_tests.rb
Requires ruby-libvirt 0.6.0 plus this patch:
https://www.redhat.com/archives/libvir-list/2016-January/msg00147.html
Closes #8
> Retrieve VM IP address using libvirt

- lib/fog/libvirt/models/compute/server.rb
Closes: https://github.com/fog/fog-libvirt/issues/16
> Fix error getting IP addresses when using provided authentication

- .travis.yml
- lib/fog/libvirt/models/compute/server.rb
- minitests/server/user_data_iso_test.rb
When the default pool is configured to a location other than
/var/lib/libvirt/images, the iso_dir is now set to the uploaded location of the
user-data image rather than defaulting to default_iso_dir.
> Set iso_dir from image path in user-data ISO upload

- lib/fog/libvirt/requests/compute/list_domains.rb
This is a followup to #15. This fixes two more areas that are susceptible to Libvirt exceptions when libvirt is being used by multiple processes. For example, multiple instances of vagrant with the vagrant-libvirt plugin.
I have been running CI tests with this change for the past couple days with pretty good success.
> catch Libvirt exceptions in list_domains to protect against race conditions

- lib/fog/libvirt/models/compute/server.rb
We shouldn't error out when some domain exists and has such a
configuration. Fixes:
closes #21
> Allow the boot order to contain 'fd' (floppy).

- lib/fog/libvirt/requests/compute/upload_volume.rb
Currently volume uploads end up empty since ruby-libvirt returns the
value passed in from the block
https://www.redhat.com/archives/libvir-list/2016-June/msg00678.html
Since this is zero libvirtd assumes the upload is finished before it
even started.
We can work around this by returning the string length. This will
continue to work with fixed ruby-libvirt since errors are indicated with
negative values.
> image_upload: Always return the number of bytes read

- fog-libvirt.gemspec
ruby-libvirt 0.7.0 is required to correctly retrieve VM IP address using libvirt (21d1b71cc2533fa5892a1a0bba9147ab2e2dca72).
This should finally resolve the #16
> Update ruby-libvirt dependency.

- .travis.yml
- CONTRIBUTORS.md
- gemfiles/Gemfile-ruby-1.9.3
Pin some dependencies so that travis can run on older ruby versions.
> Fix breaking CI on older versions

- lib/fog/libvirt/requests/compute/update_display.rb
If the vnc keymap has been changed from auto to, for example, en-us,
calling update_display will fail with a "Call to
virDomainUpdateDeviceFlags failed: internal error cannot change keymap
setting on vnc graphics" error. This commit changes it so that if no
keymap has been passed explicitly in the options we will use the keymap
that is currently used.
> Allow update_display on VMs with non-auto keymap

- lib/fog/libvirt/compute.rb
- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/libversion.rb
- minitests/server/server_test.rb
- tests/libvirt/models/compute/server_tests.rb
Libvirt releases before 1.2.8 do not fully support the
virNetworkGetDHCPLeases used by dhcp_leases, so provide a compatibility
check to determine the version of the library in order to determine
which method to use to retrieve the mac address and then replace the
current addresses method reference with this.
Currently uses calling 'virsh verison' and regex comparison of the response to
determine whether to use the previous approach which has been restored
or the more recent method that calls dhcp_leases.
Fixes: #27
> Support older libvirt address retrieval

- fog-libvirt.gemspec
- lib/fog/libvirt/models/compute/server.rb
- minitests/server/server_test.rb
Add tests to call the ssh_ip_command and local_ip_command to ensure
that variables are reference correctly and any required dependenencies
are in place.
Include missing test dependency net::ssh, but leave it optional.
Fixes issue introduced in #29
> Test the ip_command functions success path

- lib/fog/libvirt/models/compute/templates/volume.xml.erb
- lib/fog/libvirt/models/compute/volume.rb
This would allow to remove some duplicated code in vagrant-libvirt/vagrant-libvirt/pull/868
> Allow to specify UID and GID of volume.

- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/models/compute/templates/server.xml.erb
- tests/libvirt/models/compute/server_tests.rb
If the attribute 'hugepages' is set to true, define the guest as
having its memory backed by a hugepages pool.
closes GH-6
> libvirt template: Add hugepages support

- lib/fog/libvirt/models/compute/volume.rb
This PR handles the failure caused when allocation is passed empty in foreman libvirt .
> Handle blank text in allocation

- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/models/compute/templates/server.xml.erb
Fixes #55.
This adds a `qemu-guest-agent` channel. 
It allows to instruct the VM from the hypervisor e.g. to freeze filesystems for snapshotting. 
With RHEL 7 / CentOS 7, if the agent channel is present, anaconda installs and activates the guest agent automatically. 
People might want to configure this (on / off), but I would vote to have this on by default
> Add qemu-guest-agent channel.

- lib/fog/libvirt/models/compute/README.md
- lib/fog/libvirt/models/compute/templates/server.xml.erb
- lib/fog/libvirt/requests/compute/list_domains.rb
Fixes #54.
I'm unsure what to make configurable - cache option should likely be made configurable (and could go to `ceph.conf`), but `discard` (which works only with `bus=scsi`) seems like the best default to me. 
Also, it seems deletion of volumes created this way fails with fog:
https://projects.theforeman.org/issues/12063
> Add creation of RBD volumes and document it.

- lib/fog/libvirt/models/compute/README.md
- lib/fog/libvirt/models/compute/templates/server.xml.erb
During testing I discovered that my VM can freez with heavy disk load.
I also saw the following error in the libvirt/qemu log file:
lsi_scsi: error: ORDERED queue not implemented
It appears that the SCSI driver is not very well tested or widely used
since this problem has also been seen by others roughly 9 years ago. The
suggestion back then on the "kvm" mailing list was to just use VirtIO
because it is better maintained:
https://kvm.vger.kernel.narkive.com/gh8t5TeK/virtual-scsi-disks-hangs-on-heavy-io
Signed-off-by: Florian Pritz <bluewind@xinu.at>
NOTE: I have not actually tested this patch in a deployed system, but I did test the if line in `irb`.
> Support VirtIO for ceph RBD disks

- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/models/compute/templates/server.xml.erb
This allows to push entropy from the KVM host into the VM. 
It is supported since many years and happens in-kernel without any need for configuration. Since gathering good entropy inside VMs is hard without this support, this strongly improves security and performance of encrypted connections.
> Add support for virtio-rng.

- lib/fog/libvirt/models/compute/volume.rb
- lib/fog/libvirt/requests/compute/list_volumes.rb
- tests/libvirt/models/compute/volumes_tests.rb
Change the saving of the return from get_volume to ensure the
resulting list is empty if no volume was found based on the filter
keys specified.
Update the mock to replicate similar behaviour that can be
expected to be relied upon that highlights a small number of
assumptions relying on existing mock behaviour that would not
align with real world experiences.
> Return empty collection if no matching volume found

- lib/fog/libvirt/models/compute/templates/server.xml.erb
It's already defined in the pool.
We have multiple ceph clusters in different environments, so we have many monitor groups.
This way we let the configuration manager define the pool with its mons and keep it simple.
The only issue is if you want to name the pool differently per environment and
if you want to have more than a rbd pool per host.
> Skip monitor loop if it's not defined in ceph RBD disks

- lib/fog/libvirt/requests/compute/list_networks.rb
replacing https://github.com/fog/fog-libvirt/pull/78 seems github didn't reflect amended commit for some reason
> Fixes #24 - don't fail if bridge is undefined

- lib/fog/libvirt/models/compute/server.rb
Older versions of libvirt (version 1002008 or order) or builds without dhcp leases feature compiled it are vulnerable to shell escape through for-libvirt. An attacker can execute arbitrary shell code either locally or remotely over ssh.
Luckily, most linux distributions these days have the dhcp leases feature compiled in and libvirt library in version that prevents from the affected code being executed.
This bug still deserves a fix if there's someone running an old hypervisor or calling those methods explicitly via send.
The following code prints "test" string into system log/journal by crafting a domain name to escape the shell:
```ruby
require "fog/libvirt"
compute = Fog::Compute.new(provider: :libvirt, libvirt_uri: "qemu:///system")
server = compute.servers.create(name: "test; logger …
```
> Fix shell escape vulnerability

- lib/fog/libvirt/models/compute/templates/server.xml.erb
There is no USB, PS2 or graphics output on IBM Z. The console must be configured for SCLP target in order to be able to connect to the guest.
> Add support for s390x architecture

- tests/helper.rb
- tests/helpers/formats_helper.rb
- tests/helpers/formats_helper_tests.rb
- tests/helpers/mock_helper.rb
- tests/helpers/succeeds_helper.rb
This fixes test suite failure testing against Ruby 3.0. Similar fixes were already applied into fog-aws.
https://github.com/fog/fog-aws/commit/62256219f440253e9e9815b046f83143c0dd5a5b
https://github.com/fog/fog-aws/commit/359c8e0d58f4e6a193c9fd5b889bb1c59d11c4d4
The later patch would be actually enough to fix the Ruby 3.0.0 test issues, but it does not apply cleanly. Therefore I picked also the other changes.
> Ruby 3.0.0 test suite fixes

- lib/fog/libvirt/compute.rb
I couldn't find more context behind this built-in logic that modifies the URI beyond what's written in the comment. It seems that it was introduced with the initial commit.
Despite what the comment suggests, from my own experience this logic in fact seems to make it _less_ convenient to use the library on darwin, because of the assumptions made about how libvirt runs and where does it place the socket.
At the time of writing the default Homebrew formula for libvirt by default runs in the session mode (without elevated privileges), which ends up placing the socket(s) under `~/.cache/libvirt/` directory. Alternatively the service may be launched as root, in which case the sockets end up in `/usr/local/var/run/libvirt/`. Neither of these paths seem to match the one in source code.
Either way …
> Only set darwin socket path if it actually exists

- lib/fog/libvirt/requests/compute/list_networks.rb
The problem:
```
2021-05-19T12:03:28 [I|app|60036495]   Rendered compute_resources_vms/import.html.erb within layouts/application (Duration: 228.1ms | Allocations: 54224)
2021-05-19T12:03:28 [W|app|60036495] uninitialized constant Fog::Libvirt::Error
60036495 | Did you mean?  Fog::Errors
60036495 |                IOError
60036495 |                Errno
2021-05-19T12:03:28 [I|app|60036495] Backtrace for 'uninitialized constant Fog::Libvirt::Error
60036495 | Did you mean?  Fog::Errors
60036495 |                IOError
60036495 |                Errno' error (ActionView::Template::Error): uninitialized constant Fog::Libvirt::Error
60036495 | Did you mean?  Fog::Errors
60036495 |                IOError
60036495 |                Errno
60036495 | …
```
> Exception namespace fixed for list networks

- lib/fog/libvirt/models/compute/templates/volume.xml.erb
- lib/fog/libvirt/models/compute/volume.rb
Always passing this makes it required. This breaks using libvirt via qemu:///session. By not passing it at all, it leaves it up to libvirt to deal with.
> Make volume owner and group optional

- lib/fog/libvirt/version.rb
Any objections to cutting a new release? Here is what is new:
* Shell escape vulnerability
* Support for S390x
* Modernized Ruby 2.X syntax
* Updated compatibility with Ruby 3.X
* Changes in the CI infrastructure (Github Actions)
* Fix for MacOS (Darwin) UNIX socket path
* Fix for rescue in listing network
Would you mind creating a git tag and building and pushing the gem, @geemus, if there are no objections? Thank you!
> Version 0.9.0

- lib/fog/libvirt/requests/compute/list_domains.rb
In case a virtual machine goes in to libvirt mode `pmsuspended`,
situation is not handled by fog-libvirt currently. This leads to issues
in other projects like vagrant-libvirt. Suspend mode can be either the
case if domain is set into suspend (by for example systemctl suspend) or
hypervisor sets VM into suspended mode due to lack of resources.
Full discussion:
vagrant-libvirt/vagrant-libvirt#1200
Patch adds the state to possible virtual machine states.
> Add 'pmsuspended' to possible virtual machine states.

- .rubocop.yml
- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/vm_action.rb
A call to `server.destroy` ultimately ends in a call to `virDomainUndefineFlags`. Right now there is no way to set the flags argument with which `virDomainUndefineFlags` gets called. This patch provides such an option to the caller.
This is needed to address [vagrant-libvirt#1027](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1027). Specifically, vagrant-libvirt needs to be able to set the `VIR_DOMAIN_UNDEFINE_NVRAM` flag when calling `destroy` on a domain configured with NVRAM.
There is one gotcha to this. If libvirt-ruby is built without `HAVE_VIRDOMAINUNDEFINEFLAGS` the call does not end in `virDomainUndefineFlags` but in `virDomainUndefine`. In that case a non-zero flags argument will result in an error. I have found no documentation or reference to that build flag. All I …
> Add flags option to server.destroy

- lib/fog/libvirt/requests/compute/list_pools.rb
- tests/libvirt/requests/compute/list_pools_tests.rb
Allow for an `:include_inactive` filter attribute to determine whether
to include or exclude inactive pools and handle correctly setting the
number of volumes in the case it is inactive.
Current testing approach requires modifying the internal function in
order to allow the Mock to call it to ensure it is exercised correctly.
Fixes: #12
> Use a filter to allow listing of inactive pools

- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/list_networks.rb
Given the network attribute of the nic is assumed to exist, provide this
as a filter attribute to skip querying libvirt for all networks and
instead request only the one relevant.
This can help avoid a race condition where multiple sets of vagrant
machines are being run on the same host using different networks where
during delete/destroy the networks of one are removed and yet at the
same time the other environment may attempt to access the attributes.
Relates-to: vagrant-libvirt/vagrant-libvirt#1438
> Avoid querying for all networks by default

- lib/fog/libvirt/requests/compute/list_pools.rb
- tests/libvirt/requests/compute/list_pools_tests.rb
Cannot call a private class method easily from an instance, therefore
revert back to using a standard private method, but move it into the
Shared module and include in both mock and real to allow tests to
exercise handling of inactive pools
> Ensure pool_to_attributes method can be called

- fog-libvirt.gemspec
Replaces https://github.com/fog/fog-libvirt/pull/122. By pinning to the minor version instead of the patch version we shouldn't have to bump the dependency so often.
> Update development dependency versions

- lib/fog/libvirt/models/compute/server.rb
In 085a7c89596e989921dccd33dd954afbb37df27a it became possible to pass flags to Server#destroy but if the caller didn't pass flags in opts it failed because it was essentially nil.zero? which isn't defined.
I wasn't sure if I should drop the defaults for flags in options, but decided to keep it in to "document" the API.
> Deal with no flags passed to Server#destroy

- lib/fog/libvirt/models/compute/server.rb
- tests/libvirt/models/compute/server_tests.rb
Since [QEMU version 6.0](https://wiki.qemu.org/ChangeLog/6.0#Incompatible_changes), you can't use the file block driver with block devices. It tries to detect block devices by looking at the file path.
This builds on https://github.com/fog/fog-libvirt/pull/116, but I don't have the capacity to test this myself right now.
> Fix disk type for block devices on QEMU >= 6.0

- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/list_domains.rb
- tests/libvirt/models/compute/server_tests.rb
The pc type has been deprecated and on EL9 it's even unsupported. The type on aarch64 is virt, so there we continue to rely on the default.
This PR includes https://github.com/fog/fog-libvirt/pull/94 because it's easier to build on than the current template.
Right now it's untested whether this XML actually works.
> Set the default machine type to q35 on i686 and x86_64

- lib/fog/libvirt/models/compute/server.rb
@ekohl, whist I was trying to run Foreman tests on Ruby 2.7/3.0 via GA I've noticed that sometimes `volumes` can be `[nil]`. It's probably an issue with the setup, but the fix still makes this safer.
> Fix possible nil volumes for libvirt

- lib/fog/libvirt/models/compute/server.rb
VMs with UEFI store UEFI variables in OVMF files. This flag tells Libvirt to undefine it, if it exists. This was introduced in libvirt 1.2.6, which can be found on very old EL7 systems, but those are no longer supported. EL 7.9 (only supported EL7 version) ships libvirt 4.5.
This replaces https://github.com/fog/fog-libvirt/pull/107
> Undefine NVRAM on vm destruction

- Gemfile
This version breaks our tests. The code itself continues working, so it pins in Gemfile instead of gemspec.
While the change for the test suite is ready, this allows us to do a much needed bugfix release first.
> Pin ruby-libvirt to < 0.8.3

- fog-libvirt.gemspec
According to log, it wasn't ever used.
> minitest-stub-const is not use anywhere

- lib/fog/libvirt/models/compute/server.rb
In the refactor to the XML builder a subtle bug was introduced which caused the password not to be set. This uses the correct attribute.
Came up in https://community.theforeman.org/t/error-creating-libvirt-based-guest-after-upgrading-to-3-10/38295. I'm asking the reporter to test this patch.
Fixes: 6db6f8089418 ("Replace server XML with Nokogiri::XML::Builder")
> Correct the VNC password attribute

- lib/fog/libvirt/models/compute/server.rb
If `destroy()` is called with options that doesn't contain a `flags` value then it should still default to `UNDEFINE_NVRAM`. That wasn't happening.
Fixes: 21d1bf827c03 ("Undefine NVRAM on vm destruction")
Fixes #142
> Correctly pass UNDEFINE_NVRAM when flags isn't pased

- lib/fog/libvirt/models/compute/server.rb
- tests/libvirt/models/compute/server_tests.rb
The test driver doesn't support UNDEFINE_NVRAM and I couldn't find a way to probe for the capability. This hacks around it by looking at the service uri and filters out the flag.
It also adds an explicit test since previously the exception was swallowed. A new server is created to avoid interference with other tests.
> Filter out UNDEFINE_NVRAM for test:///default

- lib/fog/libvirt/models/compute/server.rb
The value for `cpu.dig(:model, :name)` is always `nil` since that's the condition in the `if` statement. It was intended to still respect the cpu mode option passed in.
Fixes: 7a3a46b48fe7 ("Prefer CPU host pass through over explicit models")
> Allow setting cpu mode again

- .rubocop.yml
- lib/fog/libvirt/models/compute/server.rb
- lib/fog/libvirt/requests/compute/list_domains.rb
- tests/libvirt/models/compute/server_tests.rb
EFI and Secure Boot support for Libvirt. 
Required for: https://github.com/theforeman/foreman/pull/10321
> EFI & Secure Boot

- lib/fog/libvirt/compute.rb
Prior to 801ce47ed9fe1295f2753eafabdf4e97021767f7 any URL could be used when mocking and it had preconfigured responses, but this regressed and could cause real system connections to go through.
This forces the URL to use the test:// scheme which still allows the use of test:///path/to/host/definitions as documented.
Fixes: 801ce47ed9fe ("Use test:///default in tests")
Reference: https://libvirt.org/uri.html#test-test-uris
> Force test:// URI to be used in mocked connections

- lib/fog/libvirt/models/compute/server.rb
For over a decade the cirrus driver has been considered outdated and the vga driver is preferred. A common alternative is qxl, but that implies the use of spice which isn't shipped in at least RHEL.
It leaves out the vram and relies on libvirt to set a sane default.
At this moment I haven't tested it, but it came out of https://github.com/fog/fog-libvirt/pull/71.
Link: https://www.kraxel.org/blog/2014/10/qemu-using-cirrus-considered-harmful/
> Update default video device to vga
